"""add intervention outcomes

Revision ID: 174e98e942ac
Revises: d44f3d6f27f8
Create Date: 2026-09-08 11:11:09.933483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174e98e942ac'
down_revision: Union[str, Sequence[str], None] = 'd44f3d6f27f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interventions', sa.Column('outcome', sa.String(length=30), nullable=True))
    op.add_column('interventions', sa.Column('outcome_notes', sa.Text(), nullable=True))
    op.add_column('interventions', sa.Column('outcome_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'outcome_date')
    op.drop_column('interventions', 'outcome_notes')
    op.drop_column('interventions', 'outcome')
    # ### end Alembic commands ###
