"""add intervention due date

Revision ID: d44f3d6f27f8
Revises: ade100efac2e
Create Date: 2026-09-08 10:47:54.368429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44f3d6f27f8'
down_revision: Union[str, Sequence[str], None] = 'ade100efac2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interventions', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interventions', 'due_date')
    # ### end Alembic commands ###
